name: absensi_karyawan_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ================= CORE =================
  intl: ^0.20.2
  dio: ^5.9.0
  http: ^1.6.0
  equatable: ^2.0.7
  logging: ^1.3.0

  # ================= STATE & ROUTING =================
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  go_router: ^17.0.0

  # ================= DEVICE & FEATURE =================
  camera: ^0.11.3
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  open_file: ^3.3.2

  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.4

  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0

  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0

  table_calendar: ^3.2.0

  # ================= NOTIFICATION =================
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
